FROM node:22-trixie-slim AS base
WORKDIR /app

RUN groupadd -g 972 docker || groupmod -g 972 docker
RUN usermod -aG docker node

RUN apt update -y &&  apt install -y curl
RUN npm install -g bun@1.3.6

FROM base AS runner
WORKDIR /app

COPY --chown=node:node package.json bun.lock ./
RUN bunx -y playwright@1.57.0 install --with-deps

RUN chown -R node:node /app

USER node
EXPOSE 5173

CMD ["sleep", "infinity"]
