FROM node:22-trixie-slim AS base

ARG VITE_BUILD_MODE=dev
RUN apt update -y &&  apt install -y git ffmpeg
SHELL ["/bin/bash", "-c"]

RUN npm install -g bun@1.3.3

FROM base AS runner

WORKDIR /app

COPY package.json bun.lock ./
RUN bun i
RUN bunx playwright install --with-deps

RUN chown -R node:node /app

USER node
EXPOSE 5173

CMD ["sleep", "infinity"]
