FROM node:22-bookworm AS base
RUN npm install -g bun@1.3.6

RUN bunx playwright install-deps

FROM base AS builder
USER node
WORKDIR /app

COPY --chown=node:node package.json bun.lock ./

RUN bun i --frozen-lockfile

RUN bunx playwright install

COPY --chown=node:node . .

FROM base AS runner
USER node
WORKDIR /app

ENTRYPOINT bun run test:ci
