FROM node:22-alpine3.23 AS base
RUN npm install -g bun@1.3.3

FROM base AS test
WORKDIR /app

COPY --chown=node:node package.json bun.lock ./

RUN bun i --frozen-lockfile
COPY --chown=node:node . .

RUN bunx -y playwright@1.57.0 install --with-deps
CMD ["bun", "run", "test"]
