FROM node:22-trixie-slim AS base
RUN npm install -g bun@1.3.3

FROM base AS test
WORKDIR /app

COPY --chown=node:node package.json bun.lock ./

RUN bun i --frozen-lockfile
COPY --chown=node:node . .

RUN bunx playwright install --with-deps

CMD ["bun", "run", "test"]
