volumes:
  postgres-data:
  sonnarqube-data:
  sonnarqube-logs:

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      target: production
      args:
        VITE_BUILD_MODE: prod
    depends_on:
      tests:
        condition: service_completed_successfully
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --quiet --tries=1 --spider http://0.0.0.0:3000/ || exit 1",
        ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s

  tests:
    build:
      context: .
      dockerfile: dockerfile
      target: test
      args:
        VITE_BUILD_MODE: dev
