FROM node:22-alpine3.22 AS base

RUN npm install -g bun@latest

RUN adduser -D -H -S node || echo "Log: Usuário 'node' já existe, continuando..."
USER node

WORKDIR /app


FROM base AS test

ARG VITE_BUILD_MODE=dev

COPY --chown=node:node ./package.json ./bun.lock ./

RUN bun i --frozen-lockfile

COPY . .

ENTRYPOINT ["bun", "run", "test"]
